title: Max Schons
description: Things worth sharing
theme: minima
markdown: kramdown
permalink: /:path/:basename

exclude:
  - README.md
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - docs/
  - "*.tsv"

url: "https://mxschons.github.io/max-schons-public"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at

include:
  - _tsv_pages
  - _faq_pages
