title: Max Schons
description: Things worth sharing
author:
  name: ""
  email: ""

show_excerpts: false
minima:
  social_links: []
theme: minima
markdown: kramdown
permalink: /:path/:basename

exclude:
  - README.md
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - docs/
  - "*.tsv"

url: "https://mxschons.github.io"
baseurl: "/max-schons-public"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at

include:
  - _tsv_pages
  - _faq_pages
  - _area_pages

header_pages:
  - _area_pages/global.md
  - _area_pages/life-admin.md
  - _area_pages/social.md
  - _area_pages/travel.md
  - _area_pages/self-care.md
  - _area_pages/professional.md
  - _faq_pages/all.md
